"""primeira migracao

Revision ID: ac63860b35dd
Revises: 
Create Date: 2025-12-29 21:33:52.686248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac63860b35dd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simbolos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('simbolo', sa.String(), nullable=True),
    sa.Column('valor_limite', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simbolos')
    # ### end Alembic commands ###
